### ISSUE TITLE
红米无法使用

### ISSUE THREAD

**Issue by Scalpelcn** [dacer/SimplePomodoro-android#1]
红米，安装成功，点击图标直接报错，很抱歉，程序无法运行

**Comment by dacer** [comment]
是编译源码后运行的还是我发布的版本？

**Comment by Scalpelcn** [comment]
发行版本，是我推荐给我的一个朋友，他给我反应的

**Comment by dacer** [comment]
很费解啊，我也没调用什么特殊的东西..
没有实机调试真想不出问题是出在哪儿@_@

**Comment by dacer** [comment]
在Testin测试完毕，原生红米应该没有问题，恐怕是限制了软件的某些权限或组件出现的问题。

**Comment by Scalpelcn** [comment]
这个很有可能，谢谢
