### ISSUE TITLE
help:怎么如何添加Google账号？

### ISSUE THREAD

**Issue by haibinpark** [dacer/SimplePomodoro-android#2]
我用的小米手机，在开启软件后，我没找如何添加Google账号！我主要想同步google task！

**Comment by dacer** [comment]
设置中开启后下拉Task列表即可

**Comment by haibinpark** [comment]
我开启后怎么出现程序闪退呢？

**Comment by dacer** [comment]
请更新为1.9.9.5版本，在Google play 或者 豌豆荚中

**Comment by haibinpark** [comment]
我的是在国内，没有安装google play,没辙！

**Comment by dacer** [comment]
基于安全考虑只使用了Android帐号授权方式，故请自行安装Google Play:)
